# configure server port
SERVER_PORT=8080

# configure datasource
DB_USERNAME=sbdemo
DB_PASSWORD=sbdemo@123
DB_HOST=localhost
DB_PORT=5432
DB_NAME=videocourse_db
SPRING_DATASOURCE_URL=jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}

# configure file system and classpath resources
FILE_SERVER_PATH=/Users/macbookpro/Backend with Spring/Spring Project/resources-testing/
FILE_CLIENT_PATH=/file/**
FILE_BASE_URI=http://localhost:8080/file/
FILE_DOWNLOAD_URI=http://localhost:8080/api/v1/files/download/

# configure mail
MAIL_HOST=smtp.gmail.com
MAIL_PORT=587
MAIL_USERNAME=suonvicheak991@gmail.com
MAIL_PASSWORD=ceno lwln bgvw jujv

# configure token key path
ACCESS_TOKEN_PRIVATE=/Users/macbookpro/Backend with Spring/Spring Project/resources-testing/keys/access-token-private
ACCESS_TOKEN_PUBLIC=/Users/macbookpro/Backend with Spring/Spring Project/resources-testing/keys/access-token-public
REFRESH_TOKEN_PRIVATE=/Users/macbookpro/Backend with Spring/Spring Project/resources-testing/keys/refresh-token-private
REFRESH_TOKEN_PUBLIC=/Users/macbookpro/Backend with Spring/Spring Project/resources-testing/keys/refresh-token-public