# configure server port
SERVER_HOST=api.cheakautomate.online
SERVER_PORT=8080

# configure datasource
DB_USERNAME=videocoursepostgres
DB_PASSWORD=videocoursepostgres@123
DB_HOST=128.199.225.145
DB_PORT=30010
DB_NAME=videocoursedb
SPRING_DATASOURCE_URL=jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}

# configure file system and classpath resources
FILE_SERVER_PATH=/workspace/
FILE_CLIENT_PATH=/file/**
FILE_BASE_URI=https://${SERVER_HOST}/file/
FILE_DOWNLOAD_URI=https://${SERVER_HOST}/api/v1/files/download

# configure mail
MAIL_HOST=smtp.gmail.com
MAIL_PORT=587
MAIL_USERNAME=suonvicheak991@gmail.com
MAIL_PASSWORD=ceno lwln bgvw jujv

# configure token key path
ACCESS_TOKEN_PRIVATE=/workspace/keys/access-token-private
ACCESS_TOKEN_PUBLIC=/workspace/keys/access-token-public
REFRESH_TOKEN_PRIVATE=/workspace/keys/refresh-token-private
REFRESH_TOKEN_PUBLIC=/workspace/keys/refresh-token-public