# configure server port
SERVER_HOST=128.199.225.145
SERVER_PORT=30011

# configure datasource
DB_USERNAME=videocoursepostgres
DB_PASSWORD=videocoursepostgres@123
DB_PORT=30010
DB_NAME=videocoursedb
SPRING_DATASOURCE_URL=jdbc:postgresql://${SERVER_HOST}:${DB_PORT}/${DB_NAME}

# configure file system and classpath resources
FILE_SERVER_PATH=/workspace/
FILE_CLIENT_PATH=/file/**
FILE_BASE_URI==http://${SERVER_HOST}:${SERVER_PORT}/file/
FILE_DOWNLOAD_URI=http://${SERVER_HOST}:${SERVER_PORT}/api/v1/files/download/

# configure mail
MAIL_HOST=smtp.gmail.com
MAIL_PORT=587
MAIL_USERNAME=suonvicheak991@gmail.com
MAIL_PASSWORD=ceno lwln bgvw jujv

# configure token key path
ACCESS_TOKEN_PRIVATE=/workspace/keys/access-token-private
ACCESS_TOKEN_PUBLIC=/workspace/keys/access-token-public
REFRESH_TOKEN_PRIVATE=/workspace/keys/refresh-token-private
REFRESH_TOKEN_PUBLIC=/workspace/keys/refresh-token-public